version: 0.2
run-as: root

env:
  variables:
    ANDROID_HOME: "/root/android-sdk"
    EMULATOR_NAME: "testAVD"
    SYSTEM_IMAGE: "system-images;android-29;google_apis;x86_64"
    TIMEOUT: 300

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 18
      python: 3.8
    commands:
      - echo "=== Instalando dependencias del sistema ==="
      - yum update -y
      - yum install -y wget unzip nc libstdc++ zlib xz-libs glibc libX11 libXrender libXext libXtst mesa-libGL

      - echo "=== Instalando Appium CLI y Driver ==="
      - npm install -g appium@next
      - appium driver install uiautomator2

      - echo "=== Instalando librerías de Robot Framework ==="
      - pip3 install --upgrade pip
      - pip3 install robotframework \
                     robotframework-appiumlibrary \
                     Appium-Python-Client

      - echo "=== Instalando Android SDK Command-Line Tools ==="
      - mkdir -p $ANDROID_HOME/cmdline-tools
      - wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
      - unzip cmdline.zip -d $ANDROID_HOME/cmdline-tools
      - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
      - rm cmdline.zip

      - echo "=== Exportando PATH ==="
      - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH

      - echo "=== Aceptando licencias y descargando SDKs ==="
      - yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
      - sdkmanager --sdk_root=$ANDROID_HOME \
          "platform-tools" "emulator" \
          "platforms;android-29" "$SYSTEM_IMAGE" \
          "build-tools;29.0.3"

  build:
    commands:
      - echo "=== Fase de compilación terminada. Preparado para correr tests. ==="
